name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * 0" # weekly on Sunday
  workflow_dispatch: # allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          card: top-langs
          path: images/top-langs.svg
          options: "layout=compact&hide=html,css,c,javascript,makefile,shell,c%2B%2B"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update stats"
          file_pattern: "images/top-langs.svg"
